services:
    postgres:
        container_name: teebay-db
        environment:
            - POSTGRES_DB=teebay
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        image: postgres:15
        restart: on-failure
        ports:
            - "8765:5432"
    server:
        container_name: teebay-server
        build: ./server
        command: sh -c "npx prisma migrate dev && npx prisma db seed && npm run start"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/teebay?schema=public
            - PORT=8000
            - JWT_TOKEN=123456789
        ports:
            - "8000:8000"
        depends_on:
            - postgres
